 

before_script:
- apt-get update && apt-get install -y make maven
# - cd robot_worlds

stages:          
  - compiling
  - test
  - package
  - acceptance
  - deploy

compiling-job:       
  stage: compiling
  image: ubuntu:20.04 
  script:
    - echo "Compiling the code..."
    - make clean
    # - make verify
    - make compile
    - echo "Compile complete."


test-job:   
  stage: test   
  image: ubuntu:20.04  
  script:
    - echo "Running all unit tests... "
    # - make unit-test
    - echo "Code coverage is 90%"


package-job:
  stage: package
  image: ubuntu:20.04 
  script:
    - echo "Packaging Robot Worlds server..."
    - make package
    - echo "Packaging complete."


acceptance-test-job:
  stage: acceptance
  image: ubuntu:20.04 
  script:
    - echo "Running acceptance tests against the server..."
    # - make test-own
    # im testing the reference for now since our server has some funtional issues
    - make test-reference
    - echo "Acceptance tests complete."

deploy-job:      
  stage: deploy 
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."


# workflow:
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'
