

before_script:
  - apt-get update 
   && apt-get upgrade -y 
    && apt-get dist-upgrade -y 
    && apt-get autoremove -y 
    && apt-get clean 
    && apt-get install -y make maven

stages:
  - compile
  - build
  - test
  - package
  - deploy

compile-job:
   stage: compile
   image: ubuntu:23.10
   script:
     - echo "Compiling the code..."
     - make compile
     - echo "Compile complete."

build-job:
  stage: build
  image: ubuntu:23.10
  script:
    - echo "Building..."
    - make clean package
    - echo "Building completed"

test-job:
   stage: test
   image: ubuntu:23.10
   script:
     - echo "Running tests..."
     - mvn test
     - echo "Running tests complete."

package-job:
   stage: package
   image: ubuntu:20.04
   script:
     - echo "Packaging Robot Worlds server..."
     - make clean
     - make package
     - echo "Packaging complete."

deploy-job:
  stage: deploy
  image: docker:27.1.0
  services:
    - docker:dind
  before_script:
    - echo "Logging into Docker repository..."
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - echo "Building the docker image..."
    - docker build -t nnyawo023/dbn_04brownfields:latest .
    - echo "Pushing the docker image..."
    - docker push nnyawo023/dbn_04brownfields:latest 
    - echo "Image successfully built and pushed."

cache:
  paths:
    - .m2/repository

workflow:
 rules:
   - if: '$CI_COMMIT_BRANCH == "main"'
