package client.commands;

import client.request.Request;
import client.robots.Robot;

public class BackCommand extends Command {
    private String argument;

    /**
     * Constructs a BackCommand object with the specified argument.
     *
     * @param argument The argument for the back command.
     */
    public BackCommand(String argument) {
        super("back");
        this.argument = argument;
    }

    /**
     * Executes the back command on the target robot and returns the corresponding Request.
     *
     * @param target The target robot to execute the back command on.
     * @return The Request generated by the back command.
     */
    @Override
    public Request execute(Robot target) {
        return new Request(target.getName(), "back", new String[]{argument});
    }
}
